version: 1.0.{build}
environment:
  matrix:
  - COMPILER: "gcc"
    MAKE_PARAMS: "zstd"
    PLATFORM: "mingw64"
  - COMPILER: "gcc"
    MAKE_PARAMS: "zstd"
    PLATFORM: "mingw32"

install:
  - ECHO Installing %COMPILER% %PLATFORM% %CONFIGURATION%
  - MKDIR bin
  - if [%COMPILER%]==[gcc] SET PATH_ORIGINAL=%PATH%
  - if [%COMPILER%]==[gcc] (
      SET "PATH_MINGW32=c:\MinGW\bin;c:\MinGW\usr\bin" &&
      SET "PATH_MINGW64=c:\msys64\mingw64\bin;c:\msys64\usr\bin" &&
      COPY C:\MinGW\bin\mingw32-make.exe C:\MinGW\bin\make.exe &&
      COPY C:\MinGW\bin\gcc.exe C:\MinGW\bin\cc.exe
    )

build_script:
  - ECHO Building %COMPILER% %PLATFORM% %CONFIGURATION%
  - if [%PLATFORM%]==[mingw32] SET PATH=%PATH_MINGW32%;%PATH_ORIGINAL% 
  - if [%PLATFORM%]==[mingw64] SET PATH=%PATH_MINGW64%;%PATH_ORIGINAL% 
  - if [%COMPILER%]==[gcc] (
      ECHO *** &&
      ECHO *** Building %PLATFORM% &&
      ECHO *** &&
      make -v &&
      cc -v &&
      ECHO make %MAKE_PARAMS% &&
      make %MAKE_PARAMS% &&
      COPY programs\zstd.exe bin\zstd_%PLATFORM%.exe &&
      echo appveyor PushArtifact bin\zstd_%PLATFORM%.exe &&
      appveyor PushArtifact bin\zstd_%PLATFORM%.exe &&
      7z a bin.zip bin\* &&
      appveyor PushArtifact bin.zip &&
      make clean
    )

test_script:
  - ECHO Testing %COMPILER% %PLATFORM% %CONFIGURATION%

deploy:
- provider: GitHub
  tag: zstd_bin
  release: zstd Windows binary
  description: zstd Windows binary
  auth_token:
    secure: LgJo8emYc3sFnlNWkGl4/VYK3nk/8+RagcsqDlAi3xeqNGNutnKjcftjg84uJoT4
  artifact: bin.zip bin\zstd_mingw64.exe
  force_update: true
  on:
    branch: artefacts
    COMPILER: gcc
    PLATFORM: "mingw64"
