version: 1.0.{build}
environment:
  matrix:
  - COMPILER: "gcc"
    MAKE_PARAMS: "zstd"
    PLATFORM: "mingw64"
  - COMPILER: "gcc"
    MAKE_PARAMS: "zstd"
    PLATFORM: "mingw32"

install:
  - ECHO Installing %COMPILER% %PLATFORM% %CONFIGURATION%
  - MKDIR bin
  - if [%COMPILER%]==[gcc] SET PATH_ORIGINAL=%PATH%
  - if [%COMPILER%]==[gcc] (
      SET "CLANG_PARAMS=-C tests zstd fullbench fuzzer zbufftest paramgrill datagen CC=clang MOREFLAGS="--target=x86_64-w64-mingw32 -Werror -Wconversion -Wno-sign-conversion"" &&
      SET "PATH_MINGW32=c:\MinGW\bin;c:\MinGW\usr\bin" &&
      SET "PATH_MINGW64=c:\msys64\mingw64\bin;c:\msys64\usr\bin" &&
      COPY C:\MinGW\bin\mingw32-make.exe C:\MinGW\bin\make.exe &&
      COPY C:\MinGW\bin\gcc.exe C:\MinGW\bin\cc.exe
    ) else (
      IF [%PLATFORM%]==[x64] (SET ADDITIONALPARAM=/p:LibraryPath="C:\Program Files\Microsoft SDKs\Windows\v7.1\lib\x64;c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\lib\amd64;C:\Program Files (x86)\Microsoft Visual Studio 10.0\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\lib\amd64;")
    )

build_script:
  - ECHO Building %COMPILER% %PLATFORM% %CONFIGURATION%
  - if [%PLATFORM%]==[mingw32] SET PATH=%PATH_MINGW32%;%PATH_ORIGINAL% 
  - if [%PLATFORM%]==[mingw64] SET PATH=%PATH_MINGW64%;%PATH_ORIGINAL% 
  - if [%COMPILER%]==[gcc] (
      ECHO *** &&
      ECHO *** Building %PLATFORM% &&
      ECHO *** &&
      make -v &&
      cc -v &&
      ECHO make %MAKE_PARAMS% &&
      make %MAKE_PARAMS% &&
      COPY programs\zstd.exe bin\zstd_%PLATFORM%.exe &&
      appveyor PushArtifact bin\zstd_%PLATFORM%.exe &&
      make clean
    )

test_script:
  - ECHO Testing %COMPILER% %PLATFORM% %CONFIGURATION%
  - SET FUZZERTEST=-T1mn
  - if [%COMPILER%]==[gcc] (
      if [%PLATFORM%]==[mingw64] tests\fuzzer_clang.exe %FUZZERTEST%
    )
